#!/bin/bash
stages:
  - build
  - deploy

image: docker:stable

services:
  - docker:dind

build_next-mongodb-template:
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    
  stage: build
  image: docker:latest
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/next-mongodb-template" .
    - docker push "$CI_REGISTRY_IMAGE/next-mongodb-template"
  # allow_failure: false;
  # test
  when: manual
  only:
    - master

deploy_next-mongodb-template:
  stage: deploy
  image: caprover/caprover:1.8.2
  script:
   - caprover deploy -h $CAPROVER_URL -p $CAPROVER_PASS -a next-mongodb-template -i "$CI_REGISTRY_IMAGE/next-mongodb-template"
  allow_failure: false
  when: manual
  only:
    - master
  tags:
   - production
